language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes postgresql-server-dev-9.6 python3-setuptools python-dev python3-dev make gcc
  # Will clone and compile Multicorn
  - git clone git://github.com/Kozea/Multicorn.git /opt/Multicorn
  - cd /opt/Multicorn
  # `make` needs sudo and will build Multicorn with Python 2.7
  - sudo make && sudo make install
  # We can then re-install Multicorn on Python 3.x
  - sudo chown -R travis.travis /opt/Multicorn
  - export PYTHON_OVERRIDE=python3
  - python3 setup.py install
  # Back to bigquery_fdw's directory
  - cd -
  # Installing packages
  - pip install pycodestyle codecov
  - python3 setup.py install
before_script:
  # Decrypt BigQuery key
  - mkdir /opt/key/
  - openssl aes-256-cbc -K $encrypted_c2c405a197db_key -iv $encrypted_c2c405a197db_iv -in src/unittest/utils/key/key.json.enc -out /opt/key/key.json -d
  #- psql -c 'create database fdw;' -U postgres
  #- psql -f src/unittest/utils/sql/setup.sql fdw -U postgres
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
  - coverage run --branch --source=. -m unittest discover -bv
  - coverage report -m
after_success:
  - codecov
